### ISSUE TITLE
Failed setup.sh

### ISSUE THREAD

**Issue by looxon93** [cancerit/PCAP-core#21]
Hi,

I am trying to install PCAP core on Docker, because it is a dependency for cgpPindel. I successfully installed cgpBigWig since it is dependency for PCAP core. I used latest PCAP core release: 4.2.0. While running setup.sh I run into error:

Log::Message will be removed from the Perl core distribution in the next major release. Please install the separate liblog-message-perl package. It is being used at /usr/share/perl5/Log/Message/Simple.pm, line 5.
Log::Message::Item will be removed from the Perl core distribution in the next major release. Please install the separate liblog-message-perl package. It is being used at /usr/share/perl/5.18/Log/Message.pm, line 7.
Log::Message::Handlers will be removed from the Perl core distribution in the next major release. Please install the separate liblog-message-perl package. It is being used at /usr/share/perl/5.18/Log/Message/Item.pm, line 7.
Log::Message::Config will be removed from the Perl core distribution in the next major release. Please install the separate liblog-message-perl package. It is being used at /usr/share/perl/5.18/Log/Message.pm, line 8.
t/pcapCli.t ........... ok
t/pcapCoverage.t ...... ok
    # No tests run!

#Failed test 'No tests run for subtest "external process handling"'
#at t/pcapThreaded.t line 113.
"fuser" failed to start: "No such file or directory" at (eval 18) line 13.
 at /opt/PCAP-core-4.2.0/blib/lib/PCAP/Threaded.pm line 320
#Tests were run but no plan was declared and done_testing() was not seen.
#Looks like your test exited with 255 just after 7.
t/pcapThreaded.t ......
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/7 subtests

Test Summary Report
-------------------
t/pcapThreaded.t    (Wstat: 65280 Tests: 7 Failed: 1)
  Failed test:  7
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=11, Tests=64,  4 wallclock secs ( 0.06 usr  0.01 sys +  3.20 cusr  0.24 csys =  3.51 CPU)
Result: FAIL
Failed 1/11 test programs. 1/64 subtests failed.
make: *** [test_dynamic] Error 255
! Installing . failed. See /root/.cpanm/work/1521110521.10751/build.log for details. Retry with --force to force install it.
FAIL

Do you know what is problem with these tests, and how can I overcome them? My perl version is 5.18.2. 

Thank you.

**Comment by keiranmraine** [comment]
The error shows an absence of a low level unix command:

```
"fuser" failed to start: "No such file or directory" at (eval 18) line 13.
```

However can use cgpPindel from pre-built docker images as described in the cgpPindel readme:

https://github.com/cancerit/cgpPindel#docker-singularity-and-dockstore

Happy analysis!

**Comment by looxon93** [comment]
Hey, thanks for quick answer! 

I tried installing fuser, and problem remains the same. Here is error:

**Comment by looxon93** [comment]
Hey, thanks for quick answer, I really appreciate it! 

I tried installing fuser to solve the problem, but it remains the same. Here is error:

#Failed test 'No tests run for subtest "external process handling"'
#at t/pcapThreaded.t line 113.
"/usr/bin/time /tmp/n1EJQi0ZV6/main___ANON__.1.sh 1> /tmp/n1EJQi0ZV6/main___ANON__.1.out 2> /tmp/n1EJQi0ZV6/main___ANON__.1.err" unexpectedly returned exit value 127 at (eval 98) line 13.
 at /opt/PCAP-core-4.2.0/blib/lib/PCAP/Threaded.pm line 268
#Tests were run but no plan was declared and done_testing() was not seen.
#Looks like your test exited with 255 just after 7.
t/pcapThreaded.t ......
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/7 subtests

Test Summary Report
-------------------
t/pcapThreaded.t    (Wstat: 65280 Tests: 7 Failed: 1)
  Failed test:  7
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=11, Tests=64,  5 wallclock secs ( 0.07 usr  0.02 sys +  4.00 cusr  0.57 csys =  4.66 CPU)
Result: FAIL
Failed 1/11 test programs. 1/64 subtests failed.
make: *** [test_dynamic] Error 255
! Installing . failed. See /root/.cpanm/work/1521118593.10750/build.log for details. Retry with --force to force install it.
FAIL
The command '/bin/sh -c ./setup.sh ./..' returned a non-zero code: 1

I tried also to build Docker image from Dockerfile you provided:
https://github.com/cancerit/dockstore-cgpwxs/blob/develop/Dockerfile

Problem is when building Docker image I get error:
ADD failed: stat /var/lib/docker/tmp/docker-builder449632020/build/opt-build.sh: no such file or directory 
Which seems to problem linked to [issue](https://github.com/docker/for-mac/issues/1922)

**Comment by looxon93** [comment]
I build Docker image with your Dockerfile for cgp-wxs analysis successfully, thank you!

**Comment by keiranmraine** [comment]
@looxon93 , why build the image when you can just pull it?

**Comment by looxon93** [comment]
I am sorry my bad. I build image with your docker file without problem. Now, I run into error with PCAP:

`Thread 6 terminated abnormally: main=HASH(0x4936b90) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 157.
Thread 7 terminated abnormally: main=HASH(0x4a48450) at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 157.
Thread error: "/usr/bin/time /cgpwxs/HCC1143_vs_HCC1143BL/pindel/tmpPindel/logs/Sanger_CGP_Pindel_Implement_pindel_to_vcf.1.sh 1> /cgpwxs/HCC1143_vs_HCC1143BL/pindel/tmpPindel/logs/Sanger_CGP_Pindel_Implement_pindel_to_vcf.1.out 2> /cgpwxs/HCC1143_vs_HCC1143BL/pindel/tmpPindel/logs/Sanger_CGP_Pindel_Implement_pindel_to_vcf.1.err" unexpectedly returned exit value 1 at (eval 32) line 12 thread 6.
2018-03-15T17:33:45.251484319Z  at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 268
Perl exited with active threads:
1 running and unjoined
1 finished and unjoined
0 running and detached`

Here is command line: 

`ds-cgpwxs.pl -sp "Homo sapiens" -c 16 -outdir . -assembly "GRCh37" -e MT,NC_007605,hs37d5,GL% -a VAGrENT_ref_GRCh37d5_ensembl_75.tar.gz -si SNV_INDEL_ref_GRCh37d5-fragment.tar.gz -t merged-tumor.bam -tidx merged-tumor.bam.bai -n merged-normal.bam -nidx merged-normal.bam.bai -r core_ref_GRCh37d5.tar.gz`

**Comment by keiranmraine** [comment]
That is not an error with PCAP, its reporting an underlying process failed.

Look in the error files in the message:

```
/cgpwxs/HCC1143_vs_HCC1143BL/pindel/tmpPindel/logs/Sanger_CGP_Pindel_Implement_pindel_to_vcf.1.err
```

Was your HCC1143 data mapped with the same reference?  Did you use dockstore-cgpmap to map the data (the same code is in dockstore-cgpwxs)?

**Comment by looxon93** [comment]
Yes, they are both mapped to human_g1k_v37_decoy.fasta. I didn't use dockstore-cgpmap. Do I have to use it on my BAM files before running  dockstore-cgpwxs?

**Comment by looxon93** [comment]
My dockstore-cgpmap also failed when I tried to run it with these BAM files.

```
"/usr/bin/time /cgpmap/tmpMap_HCC1143/logs/PCAP_Bwa_bwa_mem.1.sh 1> /cgpmap/tmpMap_HCC1143/logs/PCAP_Bwa_bwa_mem.1.out 2> /cgpmap/tmpMap_HCC1143/logs/PCAP_Bwa_bwa_mem.1.err" unexpectedly returned exit value 1 at (eval 36) line 12. 
at /opt/wtsi-cgp/lib/perl5/PCAP/Threaded.pm line 268 
```
Here is my command line: 
`ds-cgpmap.pl -o . -r core_ref_GRCh37d5.tar.gz -i human_g1k_v37_decoy.fasta.tar.gz -s HCC1143 merged-tumor.bam merged-normal.bam`

**Comment by keiranmraine** [comment]
The errors will be in `/cgpmap/tmpMap_HCC1143/logs/PCAP_Bwa_bwa_mem.1.err` (I need to try and surface those automatically via the wrappers at some point).

Could you run:

```
tar -ztf core_ref_GRCh37d5.tar.gz
tar -ztf human_g1k_v37_decoy.fasta.tar.gz
```

**Comment by looxon93** [comment]
`tar -ztf "human_g1k_v37_decoy.fasta.tar.gz"
human_g1k_v37_decoy.fasta
human_g1k_v37_decoy.fasta.amb
human_g1k_v37_decoy.fasta.ann
human_g1k_v37_decoy.fasta.bwt
human_g1k_v37_decoy.fasta.pac
human_g1k_v37_decoy.fasta.sa`

`tar -ztf "core_ref_GRCh37d5.tar.gz"
core_ref_GRCh37d5/
core_ref_GRCh37d5/genome.fa.fai
core_ref_GRCh37d5/genome.fa.dict
core_ref_GRCh37d5/genome.fa`

**Comment by keiranmraine** [comment]
So your BWA indexes don't correlate with the rest of the reference packs.  You have to build all of the reference packs against the same reference and maintain the structure and naming conventions of the originals.  If you don't then the code can't find the files.

You need to construct archives emulating the following (the first element of the path within the archive is dropped in all cases):

For mapping (cgpmap):

```
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/core_ref_GRCh37d5.tar.gz
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/bwa_idx_GRCh37d5.tar.gz
```

For SNV/InDel (cgpwxs) analysis:

```
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/core_ref_GRCh37d5.tar.gz
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/VAGrENT_ref_GRCh37d5_ensembl_75.tar.gz
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/SNV_INDEL_ref_GRCh37d5-fragment.tar.gz
```

For CNV/SV/Subclone (cgpwgs, also includes SNV/InDel):

```
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/core_ref_GRCh37d5.tar.gz
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/VAGrENT_ref_GRCh37d5_ensembl_75.tar.gz
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/SNV_INDEL_ref_GRCh37d5-fragment.tar.gz
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/CNV_SV_ref_GRCh37d5_brass6+.tar.gz
ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/SUBCL_ref_GRCh37d5.tar.gz
```
