### ISSUE TITLE
add psmisc to install dependencies

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/PCAP-core#23]
`fuser` was introduced as a dependency at some point, its included in the `psmisc` package. This is the full list of dependencies for ubuntu 16:

```bash
apt-get -yqq install \
    build-essential \
    libbz2-dev \
    libcurl4-gnutls-dev \
    libgnutls-dev \
    liblzma-dev \
    libncurses5-dev \
    libssl-dev \
    locales \
    nettle-dev \
    wget \
    zlib1g-dev \
    curl
    libexpat1-dev \
    libgoogle-perftools-dev \
    lsof \
    time \
    psmisc
```

**Comment by drjsanger** [comment]
Found the commit https://github.com/cancerit/PCAP-core/commit/dcc59d633dda84d50cd3eafbaa6a825a8ca86816 . Also looks like `lsof` could possibly be removed from dependencies, but requires testing.

**Comment by keiranmraine** [comment]
`lsof` was swapped out for `fuser` as it is available on both ubuntu and alpine

**Comment by drjsanger** [comment]
I'm happy to hotfix today or we can add this in with one/some of the enhancement tickets?

**Comment by keiranmraine** [comment]
Not really sure we should rush doc stuff out as hotfixes unless there are several things but I don't see any other items that are likely to be going out any time soon.  If you do go ahead, probably worth getting the actual list from [dockstore-cgpmap](https://github.com/cancerit/dockstore-cgpmap/blob/develop/Dockerfile) which covers all the libs needed for the related dependencies.

**Comment by jsmedmar** [comment]
Yeah no rush, i was just pointing it out
