### ISSUE TITLE
map_threads should use all cores if possible

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/PCAP-core#41]
If you use `-t 32` and you have only one input (e.g. aligning from one bam) - `bwa_mem.pl` will just use 6 cores. Instead it should be using 32.

**Comment by keiranmraine** [comment]
Even with a single BAM as input the `-fragment` option is in use, you could get many 6 cpu instances running in parallel on the same BAM input.

If you have set the fragment value high to prevent splitting you can specify `-map_threads` to be equal.  You will not get linear performance improvement and for values >12 you should also investigate this option:

```
    -bwa_pl      -l   BWA runs ~8% quicker when using the tcmalloc library from
                      https://github.com/gperftools/ (assuming number of cores not exceeded)
                      If available specify the path to 'gperftools/lib/libtcmalloc_minimal.so'.
```
