### ISSUE TITLE
Support for Illumina's FASTQ file format

### ISSUE THREAD

**Issue by ckandoth** [cancerit/PCAP-core#44]
Hello! Thanks so much for this tool. Before we do a pull-request, I wanted to ask if you are open to merging in code that adds support for [Illumina's FASTQ file format described here](https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/NamingConvention_FASTQ-files-swBS.htm). If you would prefer to implement this, that's fine too. But we will be happy to do a PR if you confirm that you can merge it in. We'd prefer not to fork.

**Comment by keiranmraine** [comment]
Hi,

Can you clarify, are you specifically meaning the file naming convention, or do you mean the cassava style record headers?

```
@SIM:1:FCX:1:15:6329:1045:GATTACT+GTCTTAAC 1:N:0:ATCCGA
```

We're certainly willing to accept PRs.  If you could add  **very** small example file (10 records) to `t/data` along with tests confirming they behave as expected that would help speed acceptance.  IIRC bwa can interpret the elements and add it to the resulting SAM reads (but it may need a flag).

**Comment by ckandoth** [comment]
Thanks! Yes, the file naming convention. Currently, there is a [requirement here](https://github.com/cancerit/PCAP-core/blob/v3.5.2/bin/bwa_mem.pl#L313-L315) that the paired FASTQs end with `_1` and `_2`. However, all our FASTQs follow the [Illumina naming scheme](https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/NamingConvention_FASTQ-files-swBS.htm) that looks like this:
```bash
SampleName_S1_L001_R1_001.fastq.gz
SampleName_S1_L001_R2_001.fastq.gz

# For example:
T2-N_IGO_07008_BU_3_S19_R1_001.fastq.gz
T2-N_IGO_07008_BU_3_S19_R2_001.fastq.gz
```

**Comment by ckandoth** [comment]
A PR is now at https://github.com/cancerit/PCAP-core/pull/56. I'll close this issue.
