### ISSUE TITLE
Is it worth breaking up bwa_mem.pl into more steps?

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/PCAP-core#61]
This is the CPU utilization profile of `bwa_mem.pl` aligning a `180` coverage genome from a BAM file using `-bm2` on a 64 cpus machine, using `-threads 64` for all steps. 

![](https://docs.google.com/drawings/d/e/2PACX-1vTCAr29KpsNyI8Gr18lYfck-PVbsWcdtdKg7CbEDB2uchZBEOBgjwAJd80bt5W7nWDmM2r1037sFG9Q/pub?w=1121&h=398)

My questions are:

* **`bwamem`**:  by `8:00` the `bwamem` step stops using the requested resources for about 3.5h. I was wondering if its worth splitting this process into two?

* **`mark`**:  same question, is it worth splitting the `mark` step into two process?

I'm now running `bwa_mem.pl` using the `-process` and `-index` flags which facilitates requesting the right amount of compute resources per step, but wanted to check on these two points.  

--------------------------

The actual running stats:

```
 Split                              Bwamem                        
    Count |    Time* |   Memory        Count |    Time* |   Memory
        n |    total |    total            n |    total |    total
        1 | 3h22m38s |    45.8G            1 | 10h9m23s |   141.0G

 Mark                               Stats
    Count |    Time* |   Memory        Count |    Time* |   Memory
        n |    total |    total            n |    total |    total
        1 |  4h1m43s |     6.4G            1 |       0s |    65.5M
```

**Comment by keiranmraine** [comment]
If you look at the underlying commands you will find that the trailing ends are reading from a pipe.  Yes, they could be split further, however you'd add a round trip of the data to disk.

`stats` is a no-op step (other than some cleanup) since a recent switch around, but is left in place for backwards-compat.

**Comment by jsmedmar** [comment]
Ok Keiran, thanks so much for the clarification. Any clue why the `mark` step seems to use exactly half of the `-threads` passed?

**Comment by keiranmraine** [comment]
The marking step (many items in samtools) will only use threads for compression.  We don't run single lanes with more than 8-10 threads for any step, and when bwa-mem2 is finally stable we'll probably drop to 6.
